### ISSUE TITLE
Using variables - new user of Home Assistant - help required please

### ISSUE THREAD

**Issue by bellringer2** [snarky-snark/home-assistant-variables#40]
I need help please.
I am a newbie to Home Assistant so if this method of requesting help is an inappropriate thing to do please accept my apologies.
I am trying to use your variables as data to a service call but I just am not getting the result I need.
I wonder if you could please advise what I’m doing wrong.
I have included two of the service calls in the scripts.yaml. The one in bold tries to use the variables to give the same result as the one not bold.
The "lounge_tv_channel_8 works fine and an 8 is sent to my TV. The "lounge_tv_channel_9" with the variables does not work.
I can see the variables in my overview and they are set to the correct values.
[problem.txt](https://github.com/snarky-snark/home-assistant-variables/files/5475729/problem.txt)
I get the following error in the log
"Logger: homeassistant.helpers.service
Source: helpers/service.py:447
First occurred: 14:24:39 (2 occurrences)
Last logged: 14:45:21

Unable to find referenced entities var.which_remote"

**Comment by snarky-snark** [comment]
Can you paste the code that you are having issues with?

**Comment by bellringer2** [comment]
"lounge_tv_channel_9:
    alias: Lounge TV channel 9
    sequence:
      - service: remote.send_command
        data_template:
          entity_id: var.which_remote
          device: var.which_device
          command: b64:JgBYAAABJpMTEhETEhISExISEhISExETEhMRExETEhMROBITERMTERI4ETgSExE4ExIRExITERMRExITETgTEhE4EzcSNxM3EwAGHwABJkoTAAxDAAEmShMADQU`"

**Comment by snarky-snark** [comment]
Maybe try using `data` instead of `data_template`?

**Comment by bellringer2** [comment]
I tried both. Neither work.

**Comment by snarky-snark** [comment]
Sorry, I'm not sure, but I suspect this is not a problem with the var component, itself.

You might try the HA discord channels or community forums for more help with your specific problem. You will get better responses if you can put together a [minimal reproducible example](https://en.m.wikipedia.org/wiki/Minimal_working_example) of your problem. Otherwise, you are making others do a bunch of work to understand the problem which may lead to fewer people willing to help.
