### ISSUE TITLE
Is it possible to create vars dynamically using a service, python, or API call?

### ISSUE THREAD

**Issue by BranndonWork** [snarky-snark/home-assistant-variables#41]
I find myself frustrated that I have to reload my entire home assistant every time I want to add a new variable to the system. 

Is there a faster reload option? Maybe a way to create them using Python, the HA API, or a HA service call?

**Comment by snarky-snark** [comment]
Sorry, but there is not a way to create var entities without a restart. This var component abuses the HA entity system which is pretty heavy-handed. This component should really be avoided in favor of HA's native variables and scenes where possible.

A couple of suggestions:
- Use NodeRed rather than YAML as it is more flexible and doesn't require a restart of HA
- Write a python script that gives you more flexibility

In my own experience, configuring HA with YAML is an error-prone time sink, and it is not worth the trouble if you can avoid it.
