### ISSUE TITLE
Add support for unique_id attribute

### ISSUE THREAD

**Issue by Santanachia** [snarky-snark/home-assistant-variables#68]
![image](https://user-images.githubusercontent.com/4628507/162126582-98998cfe-8453-4230-9c1c-7b87551b08d5.png)

**Comment by snarky-snark** [comment]
https://www.home-assistant.io/faq/unique_id/

**Comment by RoboMagus** [comment]
I've been doing some development on this component yesterday, including to add the unique ID. It's quite an easy addition, but after playing with it I do not believe this is something we should actually want to add.

Mostly as anything that is editable through the UI is also part of the configuration of the var entities in YAML, i.e. as far as I can tell we're not missing anything by not having a unique ID for each var entity.
Second, providing a unique ID allows the user to change the entity_id of var entities. This opens up all sorts of problems with the YAML configuration and the entities in Home Assistant getting out of sync.

**Comment by Santanachia** [comment]
"we're not missing anything by not having a unique ID"
I use variables to store data that is used later in the sensor. I don't need to see them on the dashboard, and without `unique_id` I have no way to hide them.

Of course you may argue that I can manually edit the dashboard and remove variables from it, but then no new entities will automatically appear on it

**Comment by Santanachia** [comment]
p.s. "This opens up all sorts of problems (...)" There are many other integrations that have unique_id and I don't see anyone wanting to abandon it to avoid any errors.

**Comment by snarky-snark** [comment]
I tend to agree with @RoboMagus. There is a risk of causing confusion in this component by supporting `unique_id`, if not done carefully. Though, I think this confusion is a general issue with `unique_id` in Home Assistant, and so it might not be up to the var component to address that general issue.

> I use variables to store data that is used later in the sensor. I don't need to see them on the dashboard, and without `unique_id` I have no way to hide them.

Can you elaborate on how `unique_id` enables you to hide variables from the dashboard? I'm not sure I understand what the benefit is here.

I see that there are integrations that support user-defined `unique_id` attributes - namely, the `templates` and `mqtt` integrations. I think a reasonable start towards support for `unique_id` in the var component would be to allow the user to define it explicitly (rather than deriving it from `entity_id`), but revert to `entity_id`-only behavior if the `unique_id` is not present.

Before doing considering this much further, I would like to enumerate the cases where user changes through the UI and YAML might conflict and cause confusion in identifying variables. Perhaps there is a way to reduce or eliminate these issues.

Here are some references to HA documentation on `unique_id`:
- https://www.home-assistant.io/faq/unique_id/
- https://developers.home-assistant.io/docs/entity_registry_index/

**Comment by Santanachia** [comment]
@snarky-snark this image is from a custom component that has a unique_id:
![image](https://user-images.githubusercontent.com/4628507/172112671-95310ec0-cbd6-41df-ba8c-c633462df08f.png)
I can select the area where it is, I can hide it and still leave it running (and that's what I want with var)
in the variables at this point I see:
![image](https://user-images.githubusercontent.com/4628507/172113082-6b044fc5-adb5-4e25-9aaf-1803aee272fb.png)

**Comment by RoboMagus** [comment]
One way to have the best of both worlds would be to explicitly add a `unique_id` field to the variable entity configuration.
This way the option is essentially _opt-in_ and can be enabled explicitly by users who'd want to, without exposing others to the potential issues of creating duplicate entities when renaming from both the HA UI and in YAML.

Based on what I could find whilst playing with this, this solution mitigates all the issues I have against adding the unique_id for such a YAML centric component as `variables`. Though the user should take care to have actually _unique_ `unique_id`'s ofcourse.

Here's a snippet that shows the coexistence of variables both with and without `unique_id` (Note the editable status and room for `Renamed UUID Test`):
![image](https://user-images.githubusercontent.com/68224306/179357954-7aa95b33-c261-46ee-8e04-d79ad98f0f15.png)

**Comment by snarky-snark** [comment]
Added in v0.15.
